language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t weijun0827/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true weijun0827/docker-react-test npm run test -- --coverage